title: Deni's Blog
description: Deni Setiawan Personal Blog Powered By Jekyll and GitHub
author: Deni Setiawan
github: https://github.com/HeyDSN
about: Experienced Web Developer, Currently Focusing In Node.js. Skilled in Linux System Administration, Technical Support, and Back End Web Development.
disqus_shortname: zerosite
google_analytics: UA-39154729-14
avatar_url: /static/img/avatar.jpg

permalink: /:title.html

enableTags: true
tagarray: []

social:
    - icon: fa-envelope
      link: "mailto:hey@deni-setiawan.me"
    - icon: fa-github
      link: "https://github.com/HeyDSN"
    - icon: fa-facebook
      link: "https://fb.me/HeyDSN"
    - icon: fa-twitter
      link: "https://twitter.com/sukaekstrashot"
    - icon: fa-instagram
      link: "https://www.instagram.com/heydenisetiawan/"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/heydsn/"
    - icon: fa-rss
      link: "/feed.xml"

share:
  twitter_username: HeyDeniSetiawan
  fb_appid: 352113115188304

urls:
    #- text: About Me
    #  url: /about/
    - text: Posts Category
      url: /category/
    - text: CV
      url: /cv.html
    #- text: XML Feed
    #  url: /feed.xml
    #- text: Sitemap
    #  url: /sitemap.xml

url: "https://dsn.web.id/"
baseurl: "blog"
paginate: 3
per_page: 1
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
